name: CI_resume

on: [push]
      
jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
    - name: Build docker 
      run: docker build -t docker_s -f Dockerfile .
    - name: Build pdf
      run: docker run -i docker_s /bin/bash
